name: centinelas
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.6+7

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^15.1.2
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_bloc: ^9.1.1
  uuid: ^4.2.2
  equatable: ^2.0.5
  either_dart: ^1.0.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_ui_auth: ^1.12.1
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.2.17
  firebase_ui_oauth_apple: ^1.2.17
  sign_in_button: ^3.2.0
  provider: ^6.1.1
  http: ^1.2.1
  get_it: ^8.0.3
  cloud_firestore: ^5.3.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.8
  flutter_styled_toast: ^2.2.1
  adaptive_dialog: ^2.0.0
  firebase_database: ^11.1.0
  url_launcher: ^6.2.4
  flutter_launcher_icons: ^0.14.3
  location: ^8.0.0
  google_maps_flutter: ^2.5.3
  permission_handler: ^12.0.0+1
  firebase_messaging: ^15.1.0
  maps_launcher: ^3.0.0+1
  webview_flutter: ^4.7.0
  firebase_crashlytics: ^4.1.0
  firebase_analytics: ^11.3.0
  device_info_plus: ^11.4.0
  cloud_functions: ^5.1.0
  firebase_storage: ^12.2.0
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21