name: centinelas_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_bloc: ^8.1.3
  uuid: ^4.2.2
  equatable: ^2.0.5
  either_dart: ^1.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_ui_auth: ^1.12.1
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.2.17
  firebase_ui_oauth_apple: ^1.2.17
  sign_in_button: ^3.2.0
  provider: ^6.1.1
  http: ^1.1.2
  get_it: ^7.6.6
  cloud_firestore: ^4.14.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  shared_preferences: ^2.2.2
  flutter_styled_toast: ^2.2.1
  # hive, json_annotation?

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true