// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQXpZgWM5Cz4U_MXNJbvTzUT0BAgHPqFA',
    appId: '1:908225121225:web:bef24103107052d0d33618',
    messagingSenderId: '908225121225',
    projectId: 'centinelas-27d9b',
    authDomain: 'centinelas-27d9b.firebaseapp.com',
    storageBucket: 'centinelas-27d9b.appspot.com',
    measurementId: 'G-MR7XZ39BTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcYsmnYaiEHn7900vbsr_urCvB3Rdaffk',
    appId: '1:908225121225:android:9de82a9d1d6f8bb7d33618',
    messagingSenderId: '908225121225',
    projectId: 'centinelas-27d9b',
    storageBucket: 'centinelas-27d9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrPuR5YYwq7e0EN0GFZ5wayWqqd6pB-0E',
    appId: '1:908225121225:ios:8d2c1170d29e1464d33618',
    messagingSenderId: '908225121225',
    projectId: 'centinelas-27d9b',
    storageBucket: 'centinelas-27d9b.appspot.com',
    iosBundleId: 'centinelas.sportspromotion.com.mx.centinelasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrPuR5YYwq7e0EN0GFZ5wayWqqd6pB-0E',
    appId: '1:908225121225:ios:68a3e7d1384c2496d33618',
    messagingSenderId: '908225121225',
    projectId: 'centinelas-27d9b',
    storageBucket: 'centinelas-27d9b.appspot.com',
    iosBundleId: 'centinelas.sportspromotion.com.mx.centinelasApp.RunnerTests',
  );
}
