// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd4_a2O44ZOsDdhXS5Y0zVEB3Z7rBITrQ',
    appId: '1:917068382197:web:80061d561524863c9b2abc',
    messagingSenderId: '917068382197',
    projectId: 'centinelas-53c9b',
    authDomain: 'centinelas-53c9b.firebaseapp.com',
    storageBucket: 'centinelas-53c9b.appspot.com',
    measurementId: 'G-DJL3Q4YM40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB26FaYz82_8-WbidkCqWw1HHysh-DNK7A',
    appId: '1:917068382197:android:267ff9c4cedad4939b2abc',
    messagingSenderId: '917068382197',
    projectId: 'centinelas-53c9b',
    storageBucket: 'centinelas-53c9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfAmOm4krXWPI9elI3maYsrexSUFU6fzI',
    appId: '1:917068382197:ios:b4d8ca8e53a25bb59b2abc',
    messagingSenderId: '917068382197',
    projectId: 'centinelas-53c9b',
    storageBucket: 'centinelas-53c9b.appspot.com',
    iosBundleId: 'centinelas.sportspromotion.com.mx.centinelasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfAmOm4krXWPI9elI3maYsrexSUFU6fzI',
    appId: '1:917068382197:ios:72614123793447739b2abc',
    messagingSenderId: '917068382197',
    projectId: 'centinelas-53c9b',
    storageBucket: 'centinelas-53c9b.appspot.com',
    iosBundleId: 'centinelas.sportspromotion.com.mx.centinelasApp.RunnerTests',
  );
}
